version: "3"

services:
  elixir:
    build: ./elixir
    volumes:
      - ./../ex/midterm:/app
    ports:
      - "4000:4000"
    secrets:
      - distant_key
    depends_on:
      - db
  neovim:
    build: ./neovim
    volumes:
      - ./..:/app
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
secrets:
  distant_key:
    file: ./distant.txt
